<a href="https://colab.research.google.com/github/Sumit-Sahu90/Road-Safety-Analysis/blob/main/Day7_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:

!pip install gdown

Requirement already satisfied: gdown in /usr/local/lib/python3.12/dist-packages (5.2.0)
Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python3.12/dist-packages (from gdown) (4.13.5)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from gdown) (3.20.0)
Requirement already satisfied: requests[socks] in /usr/local/lib/python3.12/dist-packages (from gdown) (2.32.4)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from gdown) (4.67.1)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4->gdown) (2.8)
Requirement already satisfied: typing-extensions>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4->gdown) (4.15.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests[socks]->gdown) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests[socks]->gdown) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests[socks]->gdown) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests[socks]->gdown) (2025.11.12)
Requirement already satisfied: PySocks!=1.5.7,>=1.5.6 in /usr/local/lib/python3.12/dist-packages (from requests[socks]->gdown) (1.7.1)

In [3]:

import gdown

url = "https://drive.google.com/uc?id=1XXgJNTEl4p4APOAYsDXEFEk9XX-8lg07"
gdown.download(url, "accidents.csv", quiet=False)

Downloading...
From (original): https://drive.google.com/uc?id=1XXgJNTEl4p4APOAYsDXEFEk9XX-8lg07
From (redirected): https://drive.google.com/uc?id=1XXgJNTEl4p4APOAYsDXEFEk9XX-8lg07&confirm=t&uuid=5326f29d-0fc1-464c-b198-b9af5ce5e1aa
To: /content/accidents.csv
100%|██████████| 3.06G/3.06G [00:45<00:00, 66.7MB/s]

'accidents.csv'

In [4]:
import pandas as pd

chunks = pd.read_csv("/content/accidents.csv", chunksize=200000)
us_accident_df = pd.concat(chunks)

In [5]:
us_accident_df.isnull()

,ID,Source,Severity,Start_Time,End_Time,Start_Lat,Start_Lng,End_Lat,End_Lng,Distance(mi),...,Roundabout,Station,Stop,Traffic_Calming,Traffic_Signal,Turning_Loop,Sunrise_Sunset,Civil_Twilight,Nautical_Twilight,Astronomical_Twilight
0,False,False,False,False,False,False,False,True,True,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,True,True,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,True,True,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,True,True,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,True,True,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7728389,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
7728390,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
7728391,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
7728392,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
7728393,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [6]:

us_accident_df.isnull().sum()

ID                             0
Source                         0
Severity                       0
Start_Time                     0
End_Time                       0
Start_Lat                      0
Start_Lng                      0
End_Lat                  3402762
End_Lng                  3402762
Distance(mi)                   0
Description                    5
Street                     10869
City                         253
County                         0
State                          0
Zipcode                     1915
Country                        0
Timezone                    7808
Airport_Code               22635
Weather_Timestamp         120228
Temperature(F)            163853
Wind_Chill(F)            1999019
Humidity(%)               174144
Pressure(in)              140679
Visibility(mi)            177098
Wind_Direction            175206
Wind_Speed(mph)           571233
Precipitation(in)        2203586
Weather_Condition         173459
Amenity                        0
Bump                           0
Crossing                       0
Give_Way                       0
Junction                       0
No_Exit                        0
Railway                        0
Roundabout                     0
Station                        0
Stop                           0
Traffic_Calming                0
Traffic_Signal                 0
Turning_Loop                   0
Sunrise_Sunset             23246
Civil_Twilight             23246
Nautical_Twilight          23246
Astronomical_Twilight      23246
dtype: int64

In [7]:

(us_accident_df.isnull().sum()/us_accident_df.shape[0])*100

ID                        0.000000
Source                    0.000000
Severity                  0.000000
Start_Time                0.000000
End_Time                  0.000000
Start_Lat                 0.000000
Start_Lng                 0.000000
End_Lat                  44.029355
End_Lng                  44.029355
Distance(mi)              0.000000
Description               0.000065
Street                    0.140637
City                      0.003274
County                    0.000000
State                     0.000000
Zipcode                   0.024779
Country                   0.000000
Timezone                  0.101030
Airport_Code              0.292881
Weather_Timestamp         1.555666
Temperature(F)            2.120143
Wind_Chill(F)            25.865904
Humidity(%)               2.253301
Pressure(in)              1.820288
Visibility(mi)            2.291524
Wind_Direction            2.267043
Wind_Speed(mph)           7.391355
Precipitation(in)        28.512858
Weather_Condition         2.244438
Amenity                   0.000000
Bump                      0.000000
Crossing                  0.000000
Give_Way                  0.000000
Junction                  0.000000
No_Exit                   0.000000
Railway                   0.000000
Roundabout                0.000000
Station                   0.000000
Stop                      0.000000
Traffic_Calming           0.000000
Traffic_Signal            0.000000
Turning_Loop              0.000000
Sunrise_Sunset            0.300787
Civil_Twilight            0.300787
Nautical_Twilight         0.300787
Astronomical_Twilight     0.300787
dtype: float64

In [8]:

us_accident_df.drop(['End_Lat','End_Lng'],axis=1,inplace=True)

In [9]:

us_accident_df.head()

,ID,Source,Severity,Start_Time,End_Time,Start_Lat,Start_Lng,Distance(mi),Description,Street,...,Roundabout,Station,Stop,Traffic_Calming,Traffic_Signal,Turning_Loop,Sunrise_Sunset,Civil_Twilight,Nautical_Twilight,Astronomical_Twilight
0,A-1,Source2,3,2016-02-08 05:46:00,2016-02-08 11:00:00,39.865147,-84.058723,0.01,Right lane blocked due to accident on I-70 Eas...,I-70 E,...,False,False,False,False,False,False,Night,Night,Night,Night
1,A-2,Source2,2,2016-02-08 06:07:59,2016-02-08 06:37:59,39.928059,-82.831184,0.01,Accident on Brice Rd at Tussing Rd. Expect del...,Brice Rd,...,False,False,False,False,False,False,Night,Night,Night,Day
2,A-3,Source2,2,2016-02-08 06:49:27,2016-02-08 07:19:27,39.063148,-84.032608,0.01,Accident on OH-32 State Route 32 Westbound at ...,State Route 32,...,False,False,False,False,True,False,Night,Night,Day,Day
3,A-4,Source2,3,2016-02-08 07:23:34,2016-02-08 07:53:34,39.747753,-84.205582,0.01,Accident on I-75 Southbound at Exits 52 52B US...,I-75 S,...,False,False,False,False,False,False,Night,Day,Day,Day
4,A-5,Source2,2,2016-02-08 07:39:07,2016-02-08 08:09:07,39.627781,-84.188354,0.01,Accident on McEwen Rd at OH-725 Miamisburg Cen...,Miamisburg Centerville Rd,...,False,False,False,False,True,False,Day,Day,Day,Day

In [10]:
temp_df=us_accident_df[['Wind_Speed(mph)','Precipitation(in)']]
temp_df.head()

   Wind_Speed(mph)  Precipitation(in)
0              NaN               0.02
1              NaN               0.00
2              3.5                NaN
3              4.6                NaN
4              3.5                NaN

In [11]:

from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer
sample_df=temp_df.sample(n=100000, random_state=42)
reg_imputer = IterativeImputer(random_state=42)
reg_imputer.fit(sample_df)
us_accident_df[['Wind_Speed(mph)', 'Precipitation(in)']] = reg_imputer.transform(
    us_accident_df[['Wind_Speed(mph)', 'Precipitation(in)']])

us_accident_df.head()

,ID,Source,Severity,Start_Time,End_Time,Start_Lat,Start_Lng,Distance(mi),Description,Street,...,Roundabout,Station,Stop,Traffic_Calming,Traffic_Signal,Turning_Loop,Sunrise_Sunset,Civil_Twilight,Nautical_Twilight,Astronomical_Twilight
0,A-1,Source2,3,2016-02-08 05:46:00,2016-02-08 11:00:00,39.865147,-84.058723,0.01,Right lane blocked due to accident on I-70 Eas...,I-70 E,...,False,False,False,False,False,False,Night,Night,Night,Night
1,A-2,Source2,2,2016-02-08 06:07:59,2016-02-08 06:37:59,39.928059,-82.831184,0.01,Accident on Brice Rd at Tussing Rd. Expect del...,Brice Rd,...,False,False,False,False,False,False,Night,Night,Night,Day
2,A-3,Source2,2,2016-02-08 06:49:27,2016-02-08 07:19:27,39.063148,-84.032608,0.01,Accident on OH-32 State Route 32 Westbound at ...,State Route 32,...,False,False,False,False,True,False,Night,Night,Day,Day
3,A-4,Source2,3,2016-02-08 07:23:34,2016-02-08 07:53:34,39.747753,-84.205582,0.01,Accident on I-75 Southbound at Exits 52 52B US...,I-75 S,...,False,False,False,False,False,False,Night,Day,Day,Day
4,A-5,Source2,2,2016-02-08 07:39:07,2016-02-08 08:09:07,39.627781,-84.188354,0.01,Accident on McEwen Rd at OH-725 Miamisburg Cen...,Miamisburg Centerville Rd,...,False,False,False,False,True,False,Day,Day,Day,Day

In [12]:

us_accident_df[['Wind_Speed(mph)','Precipitation(in)']].head()

   Wind_Speed(mph)  Precipitation(in)
0         7.713373           0.020000
1         7.673374           0.000000
2         3.500000           0.006377
3         4.600000           0.006945
4         3.500000           0.006377

In [13]:
us_accident_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7728394 entries, 0 to 7728393
Data columns (total 44 columns):
 #   Column                 Dtype
---  ------                 -----
 0   ID                     object
 1   Source                 object
 2   Severity               int64
 3   Start_Time             object
 4   End_Time               object
 5   Start_Lat              float64
 6   Start_Lng              float64
 7   Distance(mi)           float64
 8   Description            object
 9   Street                 object
 10  City                   object
 11  County                 object
 12  State                  object
 13  Zipcode                object
 14  Country                object
 15  Timezone               object
 16  Airport_Code           object
 17  Weather_Timestamp      object
 18  Temperature(F)         float64
 19  Wind_Chill(F)          float64
 20  Humidity(%)            float64
 21  Pressure(in)           float64
 22  Visibility(mi)         float64
 23  Wind_Direction         object
 24  Wind_Speed(mph)        float64
 25  Precipitation(in)      float64
 26  Weather_Condition      object
 27  Amenity                bool
 28  Bump                   bool
 29  Crossing               bool
 30  Give_Way               bool
 31  Junction               bool
 32  No_Exit                bool
 33  Railway                bool
 34  Roundabout             bool
 35  Station                bool
 36  Stop                   bool
 37  Traffic_Calming        bool
 38  Traffic_Signal         bool
 39  Turning_Loop           bool
 40  Sunrise_Sunset         object
 41  Civil_Twilight         object
 42  Nautical_Twilight      object
 43  Astronomical_Twilight  object
dtypes: bool(13), float64(10), int64(1), object(20)
memory usage: 1.9+ GB

In [14]:

median_col=['Temperature(F)','Wind_Chill(F)', 'Humidity(%)', 'Visibility(mi)']
for col in median_col:
  us_accident_df[col]=us_accident_df[col].fillna(us_accident_df[col].median())

In [15]:

us_accident_df[median_col].isnull().sum()

Temperature(F)    0
Wind_Chill(F)     0
Humidity(%)       0
Visibility(mi)    0
dtype: int64

In [16]:


us_accident_df['Pressure(in)']=us_accident_df['Pressure(in)'].fillna(us_accident_df['Pressure(in)'].mean())

In [17]:

us_accident_df['Pressure(in)'].isnull().sum()

np.int64(0)

In [18]:
us_accident_df['Wind_Direction']=us_accident_df['Wind_Direction'].fillna(us_accident_df['Wind_Direction'].mode()[0])

In [19]:

us_accident_df['Wind_Direction'].isnull().sum()

np.int64(0)

In [20]:

most_common = us_accident_df['Weather_Condition'].mode()[0]
us_accident_df['Weather_Condition'] = us_accident_df['Weather_Condition'].fillna(most_common)

In [ ]:

us_accident_df['Weather_Timestamp']=pd.to_datetime(us_accident_df['Weather_Timestamp'],errors='coerce')
us_accident_df['Weather_Timestamp']=us_accident_df['Weather_Timestamp'].ffill()

In [22]:

us_accident_df['Weather_Timestamp'].isnull().sum()

np.int64(0)

In [23]:

us_accident_df['Weather_Timestamp'].head()

0   2016-02-08 05:58:00
1   2016-02-08 05:51:00
2   2016-02-08 06:56:00
3   2016-02-08 07:38:00
4   2016-02-08 07:53:00
Name: Weather_Timestamp, dtype: datetime64[ns]

In [24]:

us_accident_df['Start_Time']=pd.to_datetime(us_accident_df['Start_Time'],format='mixed',errors='coerce')
us_accident_df['End_Time']=pd.to_datetime(us_accident_df['End_Time'],format='mixed',errors='coerce')

In [25]:
us_accident_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7728394 entries, 0 to 7728393
Data columns (total 44 columns):
 #   Column                 Dtype
---  ------                 -----
 0   ID                     object
 1   Source                 object
 2   Severity               int64
 3   Start_Time             datetime64[ns]
 4   End_Time               datetime64[ns]
 5   Start_Lat              float64
 6   Start_Lng              float64
 7   Distance(mi)           float64
 8   Description            object
 9   Street                 object
 10  City                   object
 11  County                 object
 12  State                  object
 13  Zipcode                object
 14  Country                object
 15  Timezone               object
 16  Airport_Code           object
 17  Weather_Timestamp      datetime64[ns]
 18  Temperature(F)         float64
 19  Wind_Chill(F)          float64
 20  Humidity(%)            float64
 21  Pressure(in)           float64
 22  Visibility(mi)         float64
 23  Wind_Direction         object
 24  Wind_Speed(mph)        float64
 25  Precipitation(in)      float64
 26  Weather_Condition      object
 27  Amenity                bool
 28  Bump                   bool
 29  Crossing               bool
 30  Give_Way               bool
 31  Junction               bool
 32  No_Exit                bool
 33  Railway                bool
 34  Roundabout             bool
 35  Station                bool
 36  Stop                   bool
 37  Traffic_Calming        bool
 38  Traffic_Signal         bool
 39  Turning_Loop           bool
 40  Sunrise_Sunset         object
 41  Civil_Twilight         object
 42  Nautical_Twilight      object
 43  Astronomical_Twilight  object
dtypes: bool(13), datetime64[ns](3), float64(10), int64(1), object(17)
memory usage: 1.9+ GB

In [26]:

pd.set_option('display.max_rows', None)
(us_accident_df.isnull().sum()/us_accident_df.shape[0]*100)

ID                       0.000000
Source                   0.000000
Severity                 0.000000
Start_Time               0.000000
End_Time                 0.000000
Start_Lat                0.000000
Start_Lng                0.000000
Distance(mi)             0.000000
Description              0.000065
Street                   0.140637
City                     0.003274
County                   0.000000
State                    0.000000
Zipcode                  0.024779
Country                  0.000000
Timezone                 0.101030
Airport_Code             0.292881
Weather_Timestamp        0.000000
Temperature(F)           0.000000
Wind_Chill(F)            0.000000
Humidity(%)              0.000000
Pressure(in)             0.000000
Visibility(mi)           0.000000
Wind_Direction           0.000000
Wind_Speed(mph)          0.000000
Precipitation(in)        0.000000
Weather_Condition        0.000000
Amenity                  0.000000
Bump                     0.000000
Crossing                 0.000000
Give_Way                 0.000000
Junction                 0.000000
No_Exit                  0.000000
Railway                  0.000000
Roundabout               0.000000
Station                  0.000000
Stop                     0.000000
Traffic_Calming          0.000000
Traffic_Signal           0.000000
Turning_Loop             0.000000
Sunrise_Sunset           0.300787
Civil_Twilight           0.300787
Nautical_Twilight        0.300787
Astronomical_Twilight    0.300787
dtype: float64